fusacatan/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from material.frontend import urls as frontend_urls
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^$', TemplateView.as_view(template_name="home.html"),
        name="home"),
    url(r'^', include('zones.urls', namespace='zones')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zones/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^zone/$', views.ZoneList.as_view(), name='zone'),
	url(r'^zone/(?P<pk>[0-9]+)/$', views.ZoneDetail.as_view(),
		name='detail'),
	url(r'^zone/new$', views.ZoneCreate.as_view(), name='new'),
	url(r'^zone/edit/(?P<pk>[0-9]+)/$',
		views.ZoneUpdate.as_view(), name='edit'),
    url(r'^zone/delete/(?P<pk>[0-9]+)/$',
    	views.ZoneDelete.as_view(), name='delete'),
]

disasters/models.py
from django.db import models
from datetime import datetime

class Disaster(models.Model):
    date = models.DateTimeField(default=datetime.now)
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    deceases = models.IntegerField()
    material_losses = models.IntegerField()


    def __str__(self):
        return self.name

    class Meta:
        ordering = ('date',)

zones/models.py
from django.db import models
from datetime import datetime

class Zone(models.Model):
    date = models.DateTimeField(default=datetime.now)
    location = models.CharField(max_length=255)
    moisture = models.DecimalField(max_digits=6, decimal_places=2)
    rainfall = models.DecimalField(max_digits=6, decimal_places=2)
    trees =  models.DecimalField(max_digits=6, decimal_places=2, default=0)

    def __str__(self):
        return self.location

    class Meta:
        ordering = ('date',)

zones/forms.py
from django import forms
from .models import Zone

class ZoneForm(forms.ModelForm):
	class Meta:
		model = Zone
		fields = '__all__'

disasters/views.py
from django.shortcuts import render

# Create your views here.

zones/views.py
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from .mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from .models import Zone
from .forms import ZoneForm

class ZoneCreate(LoginRequiredMixin, CreateView):
    model = Zone
    success_url = reverse_lazy('zones:zone')
    fields = ['date', 'location', 'moisture',
    	      'rainfall', 'trees']

class ZoneList(ListView):
    model = Zone

class ZoneDetail(LoginRequiredMixin, DetailView):
    model = Zone

class ZoneUpdate(LoginRequiredMixin, UpdateView):
    model = Zone
    success_url = reverse_lazy('zones:zone')
    fields = ['date', 'location', 'moisture',
    	      'rainfall', 'trees']


class ZoneDelete(LoginRequiredMixin, DeleteView):
    model = Zone
    success_url = reverse_lazy('zones:zone')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load staticfiles %}
	<meta charset="UTF-8">
	<title>{% block page_title %}{% endblock %}</title>
	<!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

    <link href="http://addtocalendar.com/atc/1.5/atc-style-blue.css" rel="stylesheet" type="text/css">

  <!-- Compiled and minified CSS -->
  	<link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
  	<!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
	<header>
		<div class="nav-fixed">
			<nav class="blue-grey lighten-2">
		    	<div class="nav-wrapper">
              <!-- Revisar el reverse match de esta url -->
      				<a href="http://localhost:8000/" class="hide-on-large-only brand-logo lime-text logo">
                Fusacatan
              </a>
              <a href="http://localhost:8000/" class=" hide-on-med-and-down brand-logo lime-text logo">
                &nbspFusacatan
              </a>
      				<a href="#" data-activates="mobile-demo" class="button-collapse">
                <i class="material-icons">menu</i>
              </a>
      				<ul class="right hide-on-med-and-down">
                <li>
                    <!-- Revisar el reverse match de esta url -->
        						<a href="http://localhost:8000/admin/">
                      Admin
                    </a>
        				</li>
                <li>
        						<a href="#!">
                      Desastres
                    </a>
        				</li>
                <li>
        						<a href="{% url "events:event" %}">
                      Events
                    </a>
        				</li>
      				</ul>
      				<ul class="side-nav" id="mobile-demo">
                <li>
                    <!-- Revisar el reverse match de esta url -->
                    <a href="http://localhost:8000/admin/">
                      Admin
                    </a>
                </li>
                <li>
                    <a href="#!">
                      Desastres
                    </a>
                </li>
                <li>
                    <a href="#">
                      Events
                    </a>
                </li>
      				</ul>
    			</div>
  			</nav>
		</div>
	</header>

	{% block content %}{% endblock %}

	<footer class="page-footer blue-grey lighten-2">
        <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="lime-text">Fusacatan</h5>
                <p class="grey-text text-lighten-4">
                  matarón de Programacion UCundinamarca
                </p>
              </div>
              	<div class="col l4 offset-l2 s12">
              	</div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
            © 2017 MIT License
            <a class="grey-text text-lighten-4 right" target="_blank" href="#!">
              Repositorio</a>
            </div>
        </div>
    </footer>
	<!--Import jQuery before materialize.js-->
    <script type="text/javascript"  src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- Compiled and minified JavaScript -->
  	<script src="{% static 'js/materialize.js' %}"></script>
  	<script src="{% static 'js/code.js' %}"></script>
</body>
</html>

templates/events/event_confirm_delete.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row">
			<div class="col s12">

				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<p class="flow-text center">
						¿Realmente que deseas borrar el evento "{{ object }}"?
					</p>

			</div>
		</div>
		<div class="row center">
			<a class="btn red waves-effect waves-light" href="{% url "events:event"%}">
		  		Espera, no lo borres
		  		<i class="material-icons right">clear</i>
		  	</a>
		  	<div class="row"></div>
			<button class="btn green waves-effect waves-light" type="submit" value="Submit">Si, borralo de una vez
		    	<i class="material-icons right">done</i>
		  	</button>

		  	</form>
		</div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
	</div>


{% endblock %}

templates/events/event_detail.html
{% extends "base.html" %}
{% block page_title %}
	{{ event.title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row center">
			<div class="col s12 m6 ">
                <div class="row">
                    <div class="row"></div>
                    <div class="row grey">
                        <div class="row"></div>
                        <h4>{{ event.title }}</h4>
                        <p class="flow-text">
                            {{ event.description }}
                        </p>
                    </div>
                    
                </div>
                <div class="row">
                   <!-- 3. Place event data -->
                    <span class="addtocalendar btn lime ">
                        <var class="atc_event">
                            <var class="atc_date_start">{{ event.date_start }}</var>
                            <var class="atc_date_end">{{ event.date_end }}</var>
                            <var class="atc_timezone">{{ event.timezone }}</var>
                            <var class="atc_title">{{ event.title }}</var>
                            <var class="atc_description">{{ event.description }}</var>
                            <var class="atc_location">{{ event.location }}</var>
                            <var class="atc_organizer">{{ event.organizer }}</var>
                            <var class="atc_organizer_email">{{ event.email }}</var>
                        </var>
                    </span>  
                </div>
                        
            </div>

			<div class="col s12 m6">
				<p class="flow-text">
                    <i class="material-icons">content_paste</i>
					{{ event.date_start }}
				</p>
                <p class="flow-text">
                    <i class="material-icons">content_paste</i>
                    {{ event.date_end }}
                </p>
                <p class="flow-text">
                    <i class="material-icons">access_time</i>
                    {{ event.timezone }}
                </p>
                <p class="flow-text">
                    <i class="material-icons">location_on</i>
                    {{ event.location }}
                </p>
                <p class="flow-text">
                    <i class="material-icons">face</i>
                    {{ event.organizer }}
                </p>
                <p class="flow-text">
                    <i class="material-icons">contact_mail</i>
                    {{ event.email }}
                </p>
			</div>
		</div>

	</div>

	<script type="text/javascript">(function () {
            if (window.addtocalendar)if(typeof window.addtocalendar.start == "function")return;
            if (window.ifaddtocalendar == undefined) { window.ifaddtocalendar = 1;
                var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
                s.type = 'text/javascript';s.charset = 'UTF-8';s.async = true;
                s.src = ('https:' == window.location.protocol ? 'https' : 'http')+'://addtocalendar.com/atc/1.5/atc.min.js';
                var h = d[g]('body')[0];h.appendChild(s); }})();
    </script>

    
{% endblock %}

templates/events/event_form.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col s12">
                {% load materialize %}
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form.date_start|as_material:"s12 m6" }}
                    {{ form.date_end|as_material:"s12 m6" }}
                    {{ form.title|as_material:"s12 m6" }}
                    {{ form.description|as_material:"s12 m6" }}
                    {{ form.organizer|as_material:"s12 m6" }}
                    {{ form.email|as_material:"s12 m6" }}
                    {{ form.location|as_material:"s12 m6" }}
                    {{ form.timezone|as_material:"s12 m6" }}

			</div>
		</div>
		<div class="row center">
			<button class="btn waves-effect waves-light" type="submit" value="Save">Submit
		    	<i class="material-icons right">send</i>
		  	</button>
		  	</form>
		</div>
	</div>

{% endblock %}

templates/events/event_list.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row center">
			<h3 class="grey-text">Lista de eventos</h3>
		</div>
		<div class="row center">
			<a href="{% url 'events:new' %}" class="btn-large lime waves-effect accent-1 blue-grey-text">Agregar nuevo evento</a>
			<h3 class="flow-text">A continuación podrás ver los eventos mas recientes eventos:</h3>
			<div class="row"></div>
			
			<ul class="collapsible" data-collapsible="accordion">
			  {% for event in object_list %}
			  <li>
			    <div class="collapsible-header"><i class="material-icons"><i class="material-icons">developer_board</i></i>{{ event.title }}</div>
			    <div class="collapsible-body">
			    	<a href="{% url "events:detail" event.id %}">
						<i class="material-icons black-text">visibility</i>
					</a>
			    	<a href="{% url "events:edit" event.id %}">
			    		<i class="material-icons green-text">create</i>
			    	</a>
                	<a href="{% url "events:delete" event.id %}">
                		<i class="material-icons red-text">delete_sweep</i>
                	</a>
			    </div>
			  </li>

			{% endfor %}

			</ul>
		</div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>

	</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}

<div class="container">
  <div class="row">
  <div class="col s12 l6">
    <h3>Detección demprana de Desastres</h3>
    <p class="flow-text">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur tempore distinctio cum nesciunt. Odit blanditiis odio aut. Et blanditiis deserunt repellat, ea perspiciatis eveniet, illo suscipit tempore dolore, dolorem sed!
    </p>
  </div>
  <div class="col s12 l6">
    <div class="row"></div>
    <div class="row center">
      <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d31826.56648397153!2d-74.31196563405766!3d4.3507818991926985!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses!2ses!4v1494452976384" width="450" height="450" frameborder="0" style="border:20px" allowfullscreen></iframe>
    </div>
  </div>
    
  </div>
</div>

{% endblock %}

templates/zones/zone_confirm_delete.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row">
			<div class="col s12">

				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<p class="flow-text center">
						¿Realmente que deseas borrar el evento "{{ object }}"?
					</p>

			</div>
		</div>
		<div class="row center">
			<a class="btn red waves-effect waves-light" href="{% url "events:event"%}">
		  		Espera, no lo borres
		  		<i class="material-icons right">clear</i>
		  	</a>
		  	<div class="row"></div>
			<button class="btn green waves-effect waves-light" type="submit" value="Submit">Si, borralo de una vez
		    	<i class="material-icons right">done</i>
		  	</button>

		  	</form>
		</div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
	</div>


{% endblock %}

templates/zones/zone_detail.html
{% extends "base.html" %}
{% block page_title %}
	{{ event.title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row center">
			<div class="col s12 m6 ">
                <div class="row">
                    <div class="row"></div>
                    <div class="row grey">
                        <div class="row"></div>
                        <h4>{{ zone.location }}</h4>
                        <p class="flow-text">
                            {{ zone.date }}
                        </p>
                    </div>
                    
                </div>
                        
            </div>

			<div class="col s12 m6">
				<p class="flow-text">
                    <i class="material-icons">content_paste</i>
					{{ zone.moisture }}
				</p>
                <p class="flow-text">
                    <i class="material-icons">content_paste</i>
                    {{ zone.rainfall }}
                </p>
                <p class="flow-text">
                    <i class="material-icons">access_time</i>
                    {{ zone.trees }}
                </p>
			</div>
		</div>

	</div>
    
{% endblock %}

templates/zones/zone_form.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col s12">
                {% load materialize %}
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form.date|as_material:"s12 m6" }}
                    {{ form.location|as_material:"s12 m6" }}
                    {{ form.moisture|as_material:"s12 m6" }}
                    {{ form.rainfall|as_material:"s12 m6" }}
                    {{ form.trees|as_material:"s12 m6" }}

			</div>
		</div>
		<div class="row center">
			<button class="btn waves-effect waves-light" type="submit" value="Save">Submit
		    	<i class="material-icons right">send</i>
		  	</button>
		  	</form>
		</div>
	</div>

{% endblock %}

templates/zones/zone_list.html
{% extends "base.html" %}
{% block page_title %}
	{{ title }}
{% endblock %}
{% block content %}
	<div class="container">
		<div class="row center">
			<h3 class="grey-text">Lista de Zonas</h3>
		</div>
		<div class="row center">
			<a href="{% url 'zone:new' %}" class="btn-large lime waves-effect accent-1 blue-grey-text">Agregar nueva zona</a>
			<h3 class="flow-text">A continuación podrás ver los registros de las zonas del cerro:</h3>
			<div class="row"></div>
			
			<ul class="collapsible" data-collapsible="accordion">
			  {% for zone in object_list %}
			  <li>
			    <div class="collapsible-header"><i class="material-icons"><i class="material-icons">developer_board</i></i>{{ zone.location }}</div>
			    <div class="collapsible-body">
			    	<a href="{% url "zone:detail" event.id %}">
						<i class="material-icons black-text">visibility</i>
					</a>
			    	<a href="{% url "zone:edit" event.id %}">
			    		<i class="material-icons green-text">create</i>
			    	</a>
                	<a href="{% url "zone:delete" event.id %}">
                		<i class="material-icons red-text">delete_sweep</i>
                	</a>
			    </div>
			  </li>

			{% endfor %}

			</ul>
		</div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>
		<div class="row"></div>

	</div>
{% endblock %}